root: true
parser: '@typescript-eslint/parser'
plugins:
  - '@typescript-eslint'
extends:
  - 'eslint:recommended'
  - 'plugin:@typescript-eslint/recommended'
rules:
  no-extra-semi: 'off'
  '@typescript-eslint/no-extra-semi': 'off'
  '@typescript-eslint/no-empty-function': 'off'
  '@typescript-eslint/explicit-function-return-type': 'off'
  '@typescript-eslint/member-delimiter-style': 'off'
